<html>
  <head> </head>
  <body >
  <img style="position: absolute; top: 20%; left: 0;" width="5%" src="img/stock.PNG">
  <img style="position: absolute; top: 20%; left: 70px;" width="60%" src="img/projet de dev web.PNG">
  <?PHP 
    echo '<a href="main.php?lg=Fr" target="_parent" style="position: absolute; top: 30%; right: 180px;"><img src="img/Fr.png" width="30"></a>';
    echo '<a href="main.php?lg=Mr" target="_parent" style="position: absolute; top: 30%; right: 150px;"><img src="img/Mar.png" width="30"></a>';
    echo '<a href="main.php?lg=Ang" target="_parent" style="position: absolute; top: 30%; right: 210px;"><img src="img/Ang.png" width="30"></a>';
    echo '<a href="main.php?lg=Esp" target="_parent" style="position: absolute; top: 30%; right: 240px;"><img src="img/Esp.png" width="30"></a>';
    ?>
  <img style="position: absolute; top: 20%; right: 0;" width="10%" src="img/NAMEPIC.PNG">
</body>
</html>
